// The problem: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function evenFibSum(term1, term2) {

var term3 = term2;
var sum = 0;

while (term3<4000000) {
    
    if (term3 % 2 === 0) {
        sum+=term3;
    }
    
    term3 = term1+term2;    
    
    term1 = term2;
        
    term2 = term3;
    

    }

    return sum;
}

console.log(evenFibSum(1,2));
